language: node_js
notifications:
  email: false
node_js:
  - '9'
before_script:
  - echo 'Europe/London' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
before_install:
  - export TZ=Europe/London
install:
  - travis_retry npm install
test:
  - npm test
before_deploy:
  - npm run coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master