language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
branches:
  only:
    - master
before_script:
  - echo 'Europe/London' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
before_install:
  - export TZ=Europe/London
install:
  - travis_retry npm install
test:
  - npm test
before_deploy:
  - npm run coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master